### ISSUE TITLE
AZD Java Template Validation fails

### ISSUE THREAD

**Issue by karianna** [Azure-Samples/java-microservices-aca-lab#109]
For this Java template, there are some unchecked boxes in the output when running through validation, like missing repo tags:
https://github.com/Azure-Samples/java-microservices-aca-lab/actions/runs/11496629882/job/31998619727#step:3:4812

**Comment by karianna** [comment]
@vermegi - I'm not sure if this is something you worked on?  CC @brunoborges

**Comment by vermegi** [comment]
No, this part was added by @sonwan2020 and team.

**Comment by karianna** [comment]
@sonwan2020 is this something you have some time to fix?

**Comment by sonwan2020** [comment]
@karianna OK, I am working on it

**Comment by sonwan2020** [comment]
@karianna the pipeline run into error in region swedencentral:
Your subscription is in a geography CN where access to Azure OpenAI Service is restricted for non-enterprise customers. Please speak with your account manager if you have any questions. (Code: BadRequest)

I did not meet this error when I manually run `azd up` in that region.
Do you have any idea what happend?

**Comment by karianna** [comment]
Hmmm not sure what's going on there - @brunoborges may be able to help if it's a capacity / region issue

**Comment by sonwan2020** [comment]
@brunoborges do you have any info about this restriction?
I can not create open ai instance in my sub 50328023-df85-46b6-96f5-c4566d7b063c today
I was able to do this yesterday

**Comment by sonwan2020** [comment]
The latest version of pipeline Validation Sample Workflow passed https://github.com/Azure-Samples/java-microservices-aca-lab/actions/runs/11546313931
There is known issue about the docker issue
![image](https://github.com/user-attachments/assets/3b026314-305a-43e5-8ec2-735d5cab85da)

we may just ignore
