### ISSUE TITLE
Use Spring Cloud logo to represent Spring Cloud Components - Config Server, Service Registry

### ISSUE THREAD

**Issue by selvasingh** [Azure-Samples/java-microservices-aca-lab#34]
Logo at https://upload.wikimedia.org/wikipedia/commons/7/79/Spring_Boot.svg

**Comment by selvasingh** [comment]
Here is another instance of the diagram https://azure-samples.github.io/java-microservices-aca-lab/docs/04_lab_secrets/04_openlab_secrets_aca.html

**Comment by selvasingh** [comment]
Another one https://azure-samples.github.io/java-microservices-aca-lab/docs/05_lab_security/05_openlab_security_aca.html

**Comment by vermegi** [comment]
@selvasingh  =can you double check the diagrams, we just fixed them, LGTM now.
