### ISSUE TITLE
Show logs through Log Analytics

### ISSUE THREAD

**Issue by selvasingh** [Azure-Samples/java-microservices-aca-lab#35]
Please expand this section https://azure-samples.github.io/java-microservices-aca-lab/docs/03_lab_monitor/0302.html to include the following scenarios to illustrate troubleshooting:

All app logs
Customer-service app logs
All exceptions
All inbound calls into apps on Azure Container Apps
Spring Cloud Config Server logs
Spring Cloud Service Registry logs

**Comment by vermegi** [comment]
We included the log queries for those things that surface through console and system logs. That is everything from the above list except all inbound calls. In case you know where to find these, please provide the query and we will add that as well.
