### ISSUE TITLE
Confusing arch diagram - what service is used for Spring apps?

### ISSUE THREAD

**Issue by selvasingh** [Azure-Samples/java-microservices-aca-lab#36]
https://azure-samples.github.io/java-microservices-aca-lab/docs/03_lab_monitor/0305.html appears to show AKS. Let's make these diagrams consistent

![image](https://github.com/user-attachments/assets/c2eab469-0a8e-43de-aeb3-0f171094b3db)

**Comment by selvasingh** [comment]
Here is another instance of the same diagram https://azure-samples.github.io/java-microservices-aca-lab/docs/04_lab_secrets/0404.html

**Comment by vermegi** [comment]
Diagrams were all updated with the right logos.
