### ISSUE TITLE
Provide lab walkthrough guidance

### ISSUE THREAD

**Issue by vermegi** [Azure-Samples/java-microservices-aca-lab#46]
We should provide lab walkthrough guidance to explain better the possible 'paths' learners can take through the lab modules. 

There should be a path for: 

- if you only have half a day to learn
- if you have a full day to learn
- if you want to learn how to securely set up Java applications on ACA
- if you want to integrate AI in your Spring Boot application
- ...

@selvasingh anything additional or anything I am missing here?

**Comment by sonwan2020** [comment]
#102
